/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.Home.JpHome;
import Connect.ConnectSQL;
import Interface.BanHang.jpBanHang;
import Interface.Kho.JpKho;
import Interface.QuanLy.JpQuanLy;
import Interface.Setting.JpSetting;
import Interface.ThongKe.JpThongKe;
import Models.Ban;
import Models.TaiKhoan;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinh
 */
public class frmMain extends javax.swing.JFrame {
    
    ConnectSQL cn = new ConnectSQL();
    TaiKhoan tk = new TaiKhoan();
    String user;
    String password;
    String lever;
//    public TaiKhoan loadtaikhoan(String user, String pass) {
//        return cn.GetTaiKhoan(user, pass);
//    }

    public frmMain(){
        
    }
    public frmMain(String name, String pass, String lv) {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        Clock clock = new Clock();
        fill();
        clock.start();       
        TaiKhoan tk = new TaiKhoan();
        
        txtqtv.setText(name);
        if (Integer.parseInt(lv) == 0) {
            btnQuanLy.setEnabled(false);
            btnThongKe.setEnabled(false);
            btnKho.setEnabled(false);
        }
        this.user = name;
        this.password = pass;
        this.lever = lv;
    }
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss_a");
    
    public class Clock extends Thread {
        
        public Clock() {
        }
        
        @Override
        public void run() {
            while (true) {
                int bandat = 0, banpv = 0;
                ArrayList<Ban> arrBan = cn.GetBan(0);
                for (int i = 0; i < arrBan.size(); i++) {
                    if (arrBan.get(i).getTrangThai().equals("Đang phục vụ")) {
                        banpv++;
                    }
                    if (arrBan.get(i).getTrangThai().equals("Đã đặt trước")) {
                        bandat++;
                    }
                }
                lblpv.setText(+banpv + " bàn đang phục vụ");
                lbldat.setText(+bandat + " bàn đặt trước");
                Calendar calendar = Calendar.getInstance();
                String str;
                str = sdf.format(calendar.getTime());
                lbltime.setText(str);
                try {
                    sleep(1000);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnQuanLy = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnThietLap = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtqtv = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblpv = new javax.swing.JLabel();
        lbldat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAFFEE APTECH");
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 0), null));

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/HOME.png"))); // NOI18N
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnBanHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/sellicon.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnQuanLy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/quanly.png"))); // NOI18N
        btnQuanLy.setText("QUẢN LÝ");
        btnQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/thongke.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnKho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/kho.png"))); // NOI18N
        btnKho.setText("KHO");
        btnKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoActionPerformed(evt);
            }
        });

        btnThietLap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThietLap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Setting.png"))); // NOI18N
        btnThietLap.setText("THIẾT LẬP");
        btnThietLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThietLapActionPerformed(evt);
            }
        });

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Logout.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        txtqtv.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtqtv.setForeground(new java.awt.Color(255, 0, 0));
        txtqtv.setText("txtqtv");

        lbltime.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 153, 51));
        lbltime.setText("jLabel2");

        lblpv.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblpv.setText("jLabel2");

        lbldat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbldat.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBanHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuanLy)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKho)
                        .addGap(18, 18, 18)
                        .addComponent(btnThietLap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldat)
                                    .addComponent(lbltime))
                                .addGap(27, 27, 27)
                                .addComponent(txtqtv))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblpv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDangXuat)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTrangChu)
                        .addComponent(btnBanHang)
                        .addComponent(btnQuanLy)
                        .addComponent(btnThongKe)
                        .addComponent(btnKho)
                        .addComponent(btnThietLap))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lbldat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblpv)
                                    .addComponent(btnDangXuat)))))
                    .addComponent(txtqtv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void thoat() {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng phần mềm ?", "FBI Warning", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            System.exit(0);
        }
    }
    
    public void fill() {
        home = new JpHome();
        jPanel2.add(home);
        jPanel2.updateUI();
    }
    jpBanHang banhang;
    JpHome home;
    JpKho kho;
    JpSetting Set;
    JpQuanLy ql;
    JpThongKe tke;
    
    public void reloadPanel(int i) {
        jPanel2.removeAll();
        switch (i) {
            case 1:
                if (home == null) {
                    home = new JpHome();
                }
                jPanel2.add(home);
                home.setSize(1300, 800);
                //btnBanHang.setPressedIcon(new ImageIcon("down.png"));
                jPanel2.revalidate();
                this.repaint();
                break;
            case 2:
                if (banhang == null) {
                    banhang = new jpBanHang();
                }
                jPanel2.add(banhang);
                banhang.setSize(1300, 800);
                jPanel2.revalidate();
                this.repaint();
                break;
            case 3:
                if (ql == null) {
                    ql = new JpQuanLy();
                }
                jPanel2.add(ql);
                ql.setSize(1300, 800);
                jPanel2.revalidate();
                this.repaint();
                break;
            case 4:
                if (tke == null) {
                    tke = new JpThongKe();
                }
                jPanel2.add(tke);
                tke.setSize(1300, 800);
                jPanel2.revalidate();
                this.repaint();
                break;
            case 5:
                if (kho == null) {
                    kho = new JpKho();
                }
                jPanel2.add(kho);
                kho.setSize(1300, 800);
                jPanel2.revalidate();
                this.repaint();
                break;
            case 6:
                if (Set == null) {
                    Set = new JpSetting();
                }
                jPanel2.add(Set);
                Set.setSize(1300, 800);
                jPanel2.revalidate();
                this.repaint();
                break;
            default:
                break;
        }
    }

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Đăng xuất tài khoản "+user+"?", "FBI Warning", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            this.setVisible(false);
            frmLogin login = new frmLogin();
            login.setVisible(true);
            login.thoat();
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        reloadPanel(1);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        reloadPanel(2);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyActionPerformed
        reloadPanel(3);
    }//GEN-LAST:event_btnQuanLyActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        reloadPanel(4);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoActionPerformed
        reloadPanel(5);
    }//GEN-LAST:event_btnKhoActionPerformed

    private void btnThietLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThietLapActionPerformed
        reloadPanel(6);
    }//GEN-LAST:event_btnThietLapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnThietLap;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldat;
    private javax.swing.JLabel lblpv;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel txtqtv;
    // End of variables declaration//GEN-END:variables
}
