/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Connect.ConnectSQL;
import Dao.NhomMonDAO;
import Dao.TaiKhoanDAO;
import Models.Loai;
import Models.TaiKhoan;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultRowSorter;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dinh
 */
public class Jp_QLNhomMon extends javax.swing.JPanel {

    /**
     * Creates new form Jp_QLNhomMon
     */
    public Jp_QLNhomMon() {
        initComponents();
    }

    public void getData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Loại");
        model.addColumn("Tên Loại");
        model.addColumn("Màu Sắc");
        NhomMonDAO nvDao = new NhomMonDAO();
        int soloai = 0;
        for (Loai nv : NhomMonDAO.getData()) {
            soloai++;
            model.addRow(new Object[]{nv.getMaLoai(), nv.getTenLoai(), nv.getMauSac()});
        }
        jTable1.setModel(model);
        jLTongSoLoai.setText(String.valueOf(soloai) + " Loại");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimLoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThemLoai = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLTongSoLoai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        txtMauSac = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tìm Loại");

        txtTimLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTimLoai.setText("Tìm Loại");
        txtTimLoai.setToolTipText("Tìm Loại");
        txtTimLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimLoaiFocusLost(evt);
            }
        });
        txtTimLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimLoaiKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThemLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/file_add.png"))); // NOI18N
        btnThemLoai.setText("THÊM");
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/document_edit.png"))); // NOI18N
        jButton2.setText("SỬA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnXoaLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/file_delete.png"))); // NOI18N
        btnXoaLoai.setText("XÓA");
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tổng Số Loại:");

        jLTongSoLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTongSoLoai.setForeground(new java.awt.Color(255, 0, 0));
        jLTongSoLoai.setText("Total");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/logo.png"))); // NOI18N
        jLabel3.setRequestFocusEnabled(false);

        txtMaLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMaLoai.setToolTipText("Mã Loại");

        txtTenLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTenLoai.setToolTipText("Tên Loại");

        txtMauSac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMauSac.setToolTipText("Màu Sắc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemLoai)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnXoaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLTongSoLoai)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 125, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaLoai)
                            .addComponent(txtTenLoai)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemLoai)
                                    .addComponent(jButton2)
                                    .addComponent(btnXoaLoai)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLTongSoLoai)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        getData();
    }//GEN-LAST:event_jTable1AncestorAdded

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        if (txtMaLoai.getText().equals("") || txtTenLoai.getText().equals("") || txtMauSac.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Không được rỗng");
        } else {
            try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                    PreparedStatement ps = conn.prepareCall("{call insertNhomMon(?,?,?)}")) {

                ps.setString(1, txtMaLoai.getText());
                ps.setString(2, txtTenLoai.getText());
                ps.setString(3, txtMauSac.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Thêm Loại Thành Công");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        getData();
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int i = jTable1.getSelectedRow();
            TableModel model = jTable1.getModel();
            txtMaLoai.setEnabled(false);
            txtMaLoai.setText(model.getValueAt(i, 0).toString());
            txtTenLoai.setText(model.getValueAt(i, 1).toString());
            txtMauSac.setText(model.getValueAt(i, 2).toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtTenLoai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn loại muốn cập nhật");
        } else {
            try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                    PreparedStatement ps = conn.prepareCall("{call updateNhomMon(?,?,?)}")) {
                ps.setString(1, txtTenLoai.getText());
                ps.setString(2, txtMauSac.getText());
                ps.setInt(3, Integer.parseInt(txtMaLoai.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cập Nhật Loại Thành Công");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
            getData();
            setTestfield();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        if (txtTenLoai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn loại muốn xóa");
        } else {
            try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                    PreparedStatement ps = conn.prepareCall("{call deleteNhomMon(?)}")) {
                ps.setInt(1, Integer.parseInt(txtMaLoai.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Xóa Loại Thành Công");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        getData();
        setTestfield();
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void txtTimLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimLoaiKeyReleased
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Loại");
        model.addColumn("Tên Loại");
        model.addColumn("Màu Sắc");
        String str = txtTimLoai.getText();
        jTable1.setAutoCreateRowSorter(true);
        DefaultRowSorter<?, ?> sorter = (DefaultRowSorter<?, ?>) jTable1.getRowSorter();
        sorter.setRowFilter(RowFilter.regexFilter(str));
        sorter.setSortKeys(null);
        jTable1.setRowSorter((RowSorter<? extends TableModel>) sorter);
    }//GEN-LAST:event_txtTimLoaiKeyReleased

    private void txtTimLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimLoaiFocusGained
        if (txtTimLoai.getText().equals("Tìm Loại")) {
            txtTimLoai.setText("");
        }
        txtTimLoai.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTimLoaiFocusGained

    private void txtTimLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimLoaiFocusLost
        if (txtTimLoai.getText().equals("")) {
            txtTimLoai.setText("Tìm Loại");
        }
        //[204,204,204]
        txtTimLoai.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtTimLoaiFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLTongSoLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTimLoai;
    // End of variables declaration//GEN-END:variables

    private void setTestfield() {
        txtMaLoai.setText("");
        txtMaLoai.setEnabled(false);
        txtTenLoai.setText("");
        txtMauSac.setText("");
    }
}
