/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Connect.ConnectSQL;
import Dao.ThucDonDAO;
import Interface.Run;
import Models.Loai;
import Models.ThucDon;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultRowSorter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dinh
 */
public class Jp_QLThucDon extends javax.swing.JPanel {

    ConnectSQL cn = new ConnectSQL();
    /**
     * Creates new form Jp_QLThucDon
     */
    public static Jp_QLThucDon td;

    public Jp_QLThucDon() {
        initComponents();
        Fillcbb();
        FillcbbThem();
        txtMaMon.setEnabled(false);
    }

    public void Fillcbb() {
        Vector Vcbb = cn.GetNhomMon();
        if (Vcbb != null) {
            ComboBoxModel cbbmodel = new DefaultComboBoxModel(Vcbb);
            cbbNhomMon.setModel(cbbmodel);
            add(cbbNhomMon);
        } else {
            JOptionPane.showMessageDialog(null, "Không có nhóm nào !");
        }
    }

    public void FillcbbThem() {
        Vector Vcbb = cn.GetNhomMon();
        if (Vcbb != null) {
            DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel(Vcbb);
            cbbNhomMonThem.setModel(cbbmodel);
        } else {
            JOptionPane.showMessageDialog(null, "Không có nhóm nào !");
        }
    }

    public void getData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Mã Món");
        model.addColumn("Tên Món");
        model.addColumn("Mã Loại");
        model.addColumn("Đơn Giá");
        model.addColumn("DVT");
        ThucDonDAO nvDao = new ThucDonDAO();
        int somon = 0;
        for (ThucDon nv : ThucDonDAO.getData()) {
            somon++;
            model.addRow(new Object[]{nv.getMaMon(), nv.getTenMon(), nv.getMaLoai(), new DecimalFormat("#,###,###").format(nv.getDonGia()), nv.getDVT()});
        }
        jTable1.setModel(model);
        JLTongSoMon.setText(String.valueOf(somon) + " Món");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbNhomMon = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTimThucDon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        JLTongSoMon = new javax.swing.JLabel();
        btnThemTD = new javax.swing.JButton();
        btnSuaTD = new javax.swing.JButton();
        btnXoaTD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        cbbNhomMonThem = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nhóm Món");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tìm Món");

        txtTimThucDon.setText("Tìm Món");
        txtTimThucDon.setToolTipText("Tìm Món");
        txtTimThucDon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimThucDonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimThucDonFocusLost(evt);
            }
        });
        txtTimThucDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimThucDonKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tổng Số Món: ");

        JLTongSoMon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLTongSoMon.setForeground(new java.awt.Color(255, 0, 0));
        JLTongSoMon.setText("Total");

        btnThemTD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/file_add.png"))); // NOI18N
        btnThemTD.setText("THÊM");
        btnThemTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTDActionPerformed(evt);
            }
        });

        btnSuaTD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/document_edit.png"))); // NOI18N
        btnSuaTD.setText("SỬA");
        btnSuaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTDActionPerformed(evt);
            }
        });

        btnXoaTD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/file_delete.png"))); // NOI18N
        btnXoaTD.setText("XÓA");
        btnXoaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTDActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/logo.png"))); // NOI18N

        txtTenMon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTenMon.setToolTipText("Tên Món");
        txtTenMon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenMonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenMonFocusLost(evt);
            }
        });

        txtDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDonGia.setToolTipText("Đơn Giá");
        txtDonGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDonGiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDonGiaFocusLost(evt);
            }
        });

        txtDVT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDVT.setToolTipText("DVT");
        txtDVT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDVTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDVTFocusLost(evt);
            }
        });
        txtDVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDVTActionPerformed(evt);
            }
        });

        txtMaMon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMaMon.setToolTipText("Mã Món");
        txtMaMon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaMonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaMonFocusLost(evt);
            }
        });

        cbbNhomMonThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemTD)
                        .addGap(60, 60, 60)
                        .addComponent(btnSuaTD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnXoaTD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JLTongSoMon))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbbNhomMon, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenMon)
                    .addComponent(txtDonGia)
                    .addComponent(txtDVT)
                    .addComponent(txtMaMon)
                    .addComponent(cbbNhomMonThem, 0, 129, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbbNhomMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTimThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbNhomMonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemTD)
                                    .addComponent(btnSuaTD)
                                    .addComponent(btnXoaTD)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(JLTongSoMon))))
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
private boolean validate(JTextField tf, String value, String title) {
        if (value.isEmpty()) {
            JOptionPane.showMessageDialog(null, title + " không được để trống !");
            tf.requestFocus();
            return false;
        }
        return true;
    }

    public void setTestfield() {
        txtMaMon.setText("");
        txtTenMon.setText("");
        txtDonGia.setText("");
        txtDVT.setText("");
    }
    private void btnThemTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTDActionPerformed
        if (txtTenMon.getText().equals("") || txtDonGia.getText().equals("") || txtDVT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Không được rỗng");
        } else {
            try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                    PreparedStatement ps = conn.prepareCall("{call insertThucDon(?,?,?,?}")) {
                ps.setString(1, txtTenMon.getText());
                String MaNhom = ((Loai) cbbNhomMonThem.getSelectedItem()).getMaLoai();
                ps.setString(2, MaNhom);
                ps.setInt(3, Integer.parseInt(txtDonGia.getText()));
                ps.setString(4, txtDVT.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Thêm Thành Công");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
            getData();
        }
    }//GEN-LAST:event_btnThemTDActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        getData();
    }//GEN-LAST:event_jTable1AncestorAdded

    private void btnSuaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTDActionPerformed
        if (txtTenMon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thực đơn muốn cập nhật");
        } else {
            try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                    PreparedStatement ps = conn.prepareCall("{call updateThucDon(?,?,?,?,?)}")) {
                ps.setString(1, txtTenMon.getText());
                ps.setInt(2, Integer.parseInt(txtDonGia.getText()));
                ps.setString(3, txtDVT.getText());
                ps.setInt(5, Integer.parseInt(txtMaMon.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cập Nhật Thực Đơn Thành Công");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
            getData();
            setTestfield();
        }
    }//GEN-LAST:event_btnSuaTDActionPerformed

    private void btnXoaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTDActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa thực đơn này không?", "Chú ý", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            if (txtTenMon.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn người muốn xóa");
            } else {
                try (Connection conn = DriverManager.getConnection(ConnectSQL.ConnectSQL());
                        PreparedStatement ps = conn.prepareCall("{call deleteThucDon(?)}")) {
                    ps.setInt(1, Integer.parseInt(txtMaMon.getText()));
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Xóa Tài Khoản Thành Công");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            getData();
            setTestfield();
        }
        
    }//GEN-LAST:event_btnXoaTDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int i = jTable1.getSelectedRow();
            TableModel model = jTable1.getModel();
            txtMaMon.setEnabled(false);
            txtMaMon.setText(model.getValueAt(i, 0).toString());
            txtTenMon.setText(model.getValueAt(i, 1).toString());
            txtDonGia.setText(model.getValueAt(i, 2).toString());
            txtDVT.setText(model.getValueAt(i, 3).toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtTimThucDonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimThucDonFocusGained
        if (txtTimThucDon.getText().equals("Tìm Món")) {
            txtTimThucDon.setText("");
        }
        txtTimThucDon.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTimThucDonFocusGained

    private void txtTimThucDonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimThucDonFocusLost
        if (txtTimThucDon.getText().equals("Tìm Món")) {
            txtTimThucDon.setText("");
        }
        txtTimThucDon.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTimThucDonFocusLost

    private void txtTimThucDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimThucDonKeyReleased
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Món");
        model.addColumn("Tên Món");
        model.addColumn("Mã Loại");
        model.addColumn("Đơn Giá");
        model.addColumn("DVT");
        String str = txtTimThucDon.getText();
        jTable1.setAutoCreateRowSorter(true);
        DefaultRowSorter<?, ?> sorter = (DefaultRowSorter<?, ?>) jTable1.getRowSorter();
        sorter.setRowFilter(RowFilter.regexFilter(str));
        sorter.setSortKeys(null);
        jTable1.setRowSorter((RowSorter<? extends TableModel>) sorter);
    }//GEN-LAST:event_txtTimThucDonKeyReleased

    private void txtMaMonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaMonFocusGained
        if (txtMaMon.getText().equals("Mã Món")) {
            txtMaMon.setText("");
        }
        txtMaMon.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtMaMonFocusGained

    private void txtMaMonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaMonFocusLost
        if (txtMaMon.getText().equals("")) {
            txtMaMon.setText("Mã Món");
        }
        //[204,204,204]
        txtMaMon.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtMaMonFocusLost

    private void txtTenMonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenMonFocusGained
        if (txtTenMon.getText().equals("Tên Món")) {
            txtTenMon.setText("");
        }
        txtTenMon.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTenMonFocusGained

    private void txtTenMonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenMonFocusLost
        if (txtTenMon.getText().equals("")) {
            txtTenMon.setText("Tên Món");
        }
        //[204,204,204]
        txtTenMon.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtTenMonFocusLost

    private void txtDonGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonGiaFocusGained
        if (txtDonGia.getText().equals("Đơn Giá")) {
            txtDonGia.setText("");
        }
        txtDonGia.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtDonGiaFocusGained

    private void txtDonGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonGiaFocusLost
        if (txtDonGia.getText().equals("")) {
            txtDonGia.setText("Đơn Giá");
        }
        //[204,204,204]
        txtDonGia.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtDonGiaFocusLost

    private void txtDVTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDVTFocusGained
        if (txtDVT.getText().equals("DVT")) {
            txtDVT.setText("");
        }
        txtDVT.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtDVTFocusGained

    private void txtDVTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDVTFocusLost
        if (txtDVT.getText().equals("")) {
            txtDVT.setText("DVT");
        }
        //[204,204,204]
        txtDVT.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtDVTFocusLost

    private void txtDVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDVTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLTongSoMon;
    private javax.swing.JButton btnSuaTD;
    private javax.swing.JButton btnThemTD;
    private javax.swing.JButton btnXoaTD;
    private javax.swing.JComboBox<String> cbbNhomMon;
    private javax.swing.JComboBox<String> cbbNhomMonThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtTimThucDon;
    // End of variables declaration//GEN-END:variables
}
